package Function;
import javax.swing.ImageIcon;
import java.awt.image.*;
import java.io.*;
import javax.imageio.ImageIO;
import java.net.*;
import java.awt.*;
import java.sql.*;
import java.util.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author syjt1
 */
public class Buildings extends javax.swing.JFrame {
    Connection con = null; 
    PreparedStatement poi = null; 
    PreparedStatement room = null;
    PreparedStatement type = null;
    PreparedStatement value = null;
    PreparedStatement prpsearch = null;

    ResultSet rsroom = null;
    ResultSet rstype = null;
    ResultSet rspoi = null;
    ResultSet rsvalue = null;
    ResultSet rssearch = null;

    ImageIcon img;
    String[] poi_room = new String[20];
    String[] poi_type = new String[20];
   
    public Buildings() {
        initComponents();
        con = Map_connect.Map_Con();
        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Natural Science Center/Level 1.jpg"))); // NOI18N
        picture.setSize(500,500);
        picture.setVisible(true);
        Mapscrollpanel.setViewportView(picture);
        Mapscrollpanel.setBounds(-30000, -30000, 10, 10);
        Mapscrollpanel.repaint();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Search = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        SavedPOI = new javax.swing.JButton();
        NewPOI = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        POIselector = new javax.swing.JComboBox<>();
        FloorSelector = new javax.swing.JComboBox<>();
        RoomSelector = new javax.swing.JComboBox<>();
        BuildingSelector = new javax.swing.JComboBox<>();
        BuildingName = new javax.swing.JLabel();
        Mapscrollpanel = new javax.swing.JScrollPane();
        picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));

        Search.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        SavedPOI.setText("View Saved POI");
        SavedPOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavedPOIActionPerformed(evt);
            }
        });

        NewPOI.setText("New POI");
        NewPOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPOIActionPerformed(evt);
            }
        });

        Clear.setText("Clear Filter");

        POIselector.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        POIselector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accessibility", "Washroom", "Classroom", "<POI TYPE>", "Favourites", "Custom POIs" }));
        POIselector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POIselectorActionPerformed(evt);
            }
        });

        FloorSelector.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        FloorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        FloorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloorSelectorActionPerformed(evt);
            }
        });

        RoomSelector.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        RoomSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NSC ##" }));
        RoomSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomSelectorActionPerformed(evt);
            }
        });

        BuildingSelector.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        BuildingSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural Science Center", "Western Science Center", "Middlesex College" }));
        BuildingSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingSelectorActionPerformed(evt);
            }
        });

        BuildingName.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        BuildingName.setText("Natural Science Center");

        Mapscrollpanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        Mapscrollpanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Mapscrollpanel.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                MapscrollpanelAncestorResized(evt);
            }
        });

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Natural Science Center/Level 1.jpg"))); // NOI18N
        picture.setText("picture");
        Mapscrollpanel.setViewportView(picture);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(BuildingName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Search)
                                .addGap(28, 28, 28)
                                .addComponent(POIselector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FloorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoomSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(BuildingSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SavedPOI)
                                    .addComponent(NewPOI)
                                    .addComponent(Clear))
                                .addGap(101, 101, 101)
                                .addComponent(Mapscrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BuildingName)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(POIselector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FloorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuildingSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SavedPOI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewPOI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear))
                    .addComponent(Mapscrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuildingSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingSelectorActionPerformed
        Object building_selection = BuildingSelector.getSelectedItem();
        if(building_selection == "Western Science Center"){
            BuildingName.setText((String) building_selection);
            FloorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 2", "Level 3", "Level 4","Level 5"}));
            img = new javax.swing.ImageIcon(getClass().getResource("/Western Science Center/Level 2.jpg"));
            
        }
        if(building_selection == "Middlesex College"){
            BuildingName.setText((String) building_selection);
            FloorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3","Level 4","Level 5"}));
            img = new javax.swing.ImageIcon(getClass().getResource("/Middlesex College/Level 1.jpg"));

        }
        if(building_selection == "Natural Science Center"){
            BuildingName.setText((String) building_selection);
            FloorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3"}));
            img = new javax.swing.ImageIcon(getClass().getResource("/Natural Science Center/Level 1.jpg"));
        }
            picture.setIcon(img);
            Mapscrollpanel.repaint();
    }//GEN-LAST:event_BuildingSelectorActionPerformed

    private void FloorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloorSelectorActionPerformed
     String FloorSelection = (String) FloorSelector.getSelectedItem();
     String BuildingSelection = (String) BuildingSelector.getSelectedItem();
     ArrayList<String> listroom = new ArrayList<String>();
     ArrayList<String> listpoi = new ArrayList<String>();

     String b_code =null;
     String floor =null;
     String Floorimg = "/" + BuildingSelection + "/" + FloorSelection + ".jpg";
     picture.setIcon(new javax.swing.ImageIcon(this.getClass().getResource(Floorimg)));
     Mapscrollpanel.repaint();

     if(BuildingSelection == "Western Science Center"){
         b_code = "WSC";
     }
     if(BuildingSelection == "Middlesex College"){
         b_code = "MC";
     }
     if(BuildingSelection == "Natural Science Center"){
         b_code = "NSC";
     }
     
     if(FloorSelection == "Level 1"){
         floor = "1";
     }else if(FloorSelection == "Level 2"){
         floor = "2";
     }else if(FloorSelection == "Level 3"){
         floor = "3";
     }else if(FloorSelection == "Level 4"){
         floor = "4";
     }else if(FloorSelection == "Level 5"){
         floor = "5";
     }
     
     String sql_room = "SELECT * from room WHERE floor_level ='"+floor+"' AND bd_code ='"+b_code+"';";
     String sql_type = "SELECT DISTINCT room_type from room WHERE floor_level ='"+floor+"' AND bd_code ='"+b_code+"';";
     try{
           room = con.prepareStatement(sql_room);
           type = con.prepareStatement(sql_type);

           rsroom = room.executeQuery();
           rstype = type.executeQuery();
           
           while(rsroom.next()){
               listroom.add(rsroom.getString("room_num"));

           }
           while(rstype.next()){
               listpoi.add(rstype.getString("room_type"));
           }
           
            poi_room = listroom.toArray(poi_room);
            poi_type = listpoi.toArray(poi_type);
            
            RoomSelector.setModel(new javax.swing.DefaultComboBoxModel<>(poi_room));  
            POIselector.setModel(new javax.swing.DefaultComboBoxModel<>(poi_type)); 
            
            room.close();
            type.close();
            rsroom.close();
            rstype.close();
     }catch(SQLException e){
         System.out.println("SQL Error:"+e);
    }//GEN-LAST:event_FloorSelectorActionPerformed
    
    }
    
    
    
    
    private void POIselectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POIselectorActionPerformed
        ArrayList<String> listroom = new ArrayList<String>();
        String POI = (String) POIselector.getSelectedItem();
        String sql_room = "SELECT * from room WHERE room_type LIKE ?;";
        try{
            poi = con.prepareStatement(sql_room);
            poi.setString(1,POI);
            rspoi = poi.executeQuery();
            while(rspoi.next()){
               listroom.add(rspoi.getString("room_num"));
           }
            poi_room = listroom.toArray(poi_room);
            RoomSelector.setModel(new javax.swing.DefaultComboBoxModel<>(poi_room));  
            
            poi.close();
            rspoi.close();
        }catch(Exception e){
            System.out.print(e);
        }
                           
            
          }//GEN-LAST:event_POIselectorActionPerformed

    private void SavedPOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedPOIActionPerformed
    }//GEN-LAST:event_SavedPOIActionPerformed

    private void NewPOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPOIActionPerformed
        POI obj = new POI();
        obj.setVisible(true);        
    }//GEN-LAST:event_NewPOIActionPerformed

    private void MapscrollpanelAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_MapscrollpanelAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_MapscrollpanelAncestorResized

    private void RoomSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomSelectorActionPerformed
        String Floor = (String) FloorSelector.getSelectedItem();
        String BuildingSelection = (String) BuildingSelector.getSelectedItem();
        String RoomSelection = (String) RoomSelector.getSelectedItem();
        String b_code =null;
        try{
        if(BuildingSelection == "Western Science Center"){
         b_code = "WSC";
        }
        if(BuildingSelection == "Middlesex College"){
            b_code = "MC";
        }
        if(BuildingSelection == "Natural Science Center"){
            b_code = "NSC";
        }
        String Roomimg = "/" + BuildingSelection + "/" + b_code +"/"+Floor+"/"+RoomSelection+ ".jpg";
        picture.setIcon(new javax.swing.ImageIcon(this.getClass().getResource(Roomimg)));
        Mapscrollpanel.repaint();
        
    }catch(Exception e){
            System.out.println(e);
        
    }
           
    }//GEN-LAST:event_RoomSelectorActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        String search = SearchBar.getText();
        String sql_search ="SELECT * FROM (room INNER JOIN building ON b_code = bd_code) WHERE room_num ='"+search+"';";
        try{
            prpsearch = con.prepareStatement(sql_search);
            rssearch = prpsearch.executeQuery();
            
            if(rssearch.next()){
                String Building = rssearch.getString("b_name");
                String b_code = rssearch.getString("b_code");
                String Floor =rssearch.getString("floor_level");
                String Roomimg = "/" + Building + "/" + b_code +"/Level "+Floor+"/"+search+ ".jpg";
                picture.setIcon(new javax.swing.ImageIcon(this.getClass().getResource(Roomimg)));
                Mapscrollpanel.repaint();
            }else{
                //POP up 
            }
            
        }catch(Exception e){
            System.out.print("Searching error:"+e);

        }
    }//GEN-LAST:event_SearchActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buildings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buildings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buildings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buildings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new Buildings().setVisible(true);
            }
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuildingName;
    private javax.swing.JComboBox<String> BuildingSelector;
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> FloorSelector;
    private javax.swing.JScrollPane Mapscrollpanel;
    private javax.swing.JButton NewPOI;
    private javax.swing.JComboBox<String> POIselector;
    private javax.swing.JComboBox<String> RoomSelector;
    private javax.swing.JButton SavedPOI;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel picture;
    // End of variables declaration//GEN-END:variables
}
