package Function;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author syjt1
 */
public class WSC extends javax.swing.JFrame {
    ImagePanel map;

    public WSC() {
        initComponents();
        map = new ImagePanel();
        MapPanel.add(map);
        map.setImage(new ImageIcon(this.getClass().getResource("/WSC/Level 2.jpg")).getImage());
        map.setSize(MapPanel.getWidth(),MapPanel.getHeight());
        map.setVisible(true);
        MapPanel.repaint();    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        SavedPOI = new javax.swing.JButton();
        NewPOI = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Symbols = new javax.swing.JComboBox<>();
        FloorSelector = new javax.swing.JComboBox<>();
        RoomSelector = new javax.swing.JComboBox<>();
        BuildingSelector = new javax.swing.JComboBox<>();
        Search = new javax.swing.JButton();
        MapPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Western Science Center");

        SavedPOI.setText("View Saved POI");
        SavedPOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavedPOIActionPerformed(evt);
            }
        });

        NewPOI.setText("New POI");

        Clear.setText("Clear Filter");

        Symbols.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        Symbols.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accessibility", "Washroom", "Classroom", "<POI TYPE>", "Favourites", "Custom POIs" }));
        Symbols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymbolsActionPerformed(evt);
            }
        });

        FloorSelector.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        FloorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 2", "Level 3", "Level 4", "Level 5" }));
        FloorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloorSelectorActionPerformed(evt);
            }
        });

        RoomSelector.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        RoomSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WSC ##", "Item 2", "Item 3", "Item 4" }));
        RoomSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomSelectorActionPerformed(evt);
            }
        });

        BuildingSelector.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        BuildingSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Western Science Center", "NSC - Natrual Science Center", "MC- Middlessex" }));
        BuildingSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingSelectorActionPerformed(evt);
            }
        });

        Search.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        Search.setText("Search");

        javax.swing.GroupLayout MapPanelLayout = new javax.swing.GroupLayout(MapPanel);
        MapPanel.setLayout(MapPanelLayout);
        MapPanelLayout.setHorizontalGroup(
            MapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        MapPanelLayout.setVerticalGroup(
            MapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Search)
                                .addGap(31, 31, 31)
                                .addComponent(Symbols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FloorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoomSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(BuildingSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SavedPOI)
                                    .addComponent(NewPOI)
                                    .addComponent(Clear))
                                .addGap(18, 18, 18)
                                .addComponent(MapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Symbols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FloorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuildingSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SavedPOI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewPOI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuildingSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingSelectorActionPerformed
        Object selection = BuildingSelector.getSelectedItem();
        if(selection == "NSC - Natrual Science Center"){
            Buildings obj = new Buildings();
            this.setVisible(false);
            obj.setVisible(true);
        }
        if(selection == "MC- Middlessex"){
            this.setVisible(false);
        }
    }//GEN-LAST:event_BuildingSelectorActionPerformed

    private void SavedPOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedPOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavedPOIActionPerformed

    private void RoomSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomSelectorActionPerformed

    private void FloorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloorSelectorActionPerformed
     String selection = (String) FloorSelector.getSelectedItem();
     selection = "/WSC/" + selection + ".jpg";     
     map.setImage(new ImageIcon(this.getClass().getResource(selection)).getImage());
     MapPanel.repaint();    
    }//GEN-LAST:event_FloorSelectorActionPerformed

    private void SymbolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymbolsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SymbolsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WSC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BuildingSelector;
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> FloorSelector;
    private javax.swing.JPanel MapPanel;
    private javax.swing.JButton NewPOI;
    private javax.swing.JComboBox<String> RoomSelector;
    private javax.swing.JButton SavedPOI;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JComboBox<String> Symbols;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
