package welcome;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author karanvir
 */
public class weathwmain extends javax.swing.JFrame {

    /**
     * Creates new form weathwmain
     */
    public weathwmain() {
        initComponents();
        int selected = jComboBox1.getSelectedIndex();
        String[] selected_city = new String[4];
        try {
            selected_city = weather_api.api_call(selected);
        } catch (Exception ex) {
            Logger.getLogger(weathwmain.class.getName()).log(Level.SEVERE, null, ex);
        }
        // set weather description
        weather_text.setText(selected_city[1]);
        // set current temp
        current_temp.setText(selected_city[2] + "°C");
        // set feels like
        feels_like.setText("Feels like: " + selected_city[3]);
        
        jLabel_icon_changer(selected_city[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        weather_text = new javax.swing.JLabel();
        current_temp = new javax.swing.JLabel();
        feels_like = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("weather_widget");
        setPreferredSize(new java.awt.Dimension(360, 230));

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 230));

        weather_text.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        weather_text.setForeground(new java.awt.Color(255, 255, 255));
        weather_text.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        weather_text.setText("wther_desc");
        weather_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        weather_text.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        current_temp.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        current_temp.setForeground(new java.awt.Color(255, 255, 255));
        current_temp.setText("temp");
        current_temp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        current_temp.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                current_tempComponentShown(evt);
            }
        });

        feels_like.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        feels_like.setForeground(new java.awt.Color(255, 255, 255));
        feels_like.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        feels_like.setText("feels_like");
        feels_like.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "London", "Toronto", "Montreal", "Vancouver", "Winnipeg" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setText("weather_icon");
        icon.setToolTipText("");
        icon.setMaximumSize(new java.awt.Dimension(512, 512));
        icon.setMinimumSize(new java.awt.Dimension(150, 150));
        icon.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(current_temp)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weather_text)
                    .addComponent(feels_like)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(current_temp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weather_text)
                .addGap(17, 17, 17)
                .addComponent(feels_like))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        int selected = jComboBox1.getSelectedIndex();
        String[] selected_city = new String[4];
        try {
            selected_city = weather_api.api_call(selected);
        } catch (Exception ex) {
            Logger.getLogger(weathwmain.class.getName()).log(Level.SEVERE, null, ex);
        }
        // set weather description
        weather_text.setText(selected_city[1]);
        // set current temp
        current_temp.setText(selected_city[2] + "°C");
        // set feels like
        feels_like.setText("Feels like: " + selected_city[3]);
        
        jLabel_icon_changer(selected_city[0]);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void current_tempComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_current_tempComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_current_tempComponentShown

    private void jLabel_icon_changer(String weather_type) {
        // changes image in jLabel container
        
        //determine corresponding icon
        String icon_path;
        
        switch(weather_type) {
            case "Clear":
                icon_path = "/welcom/weather_icons/clear_icon.png";
                break;
            case "Clouds":
                icon_path = "/welcome/weather_icons/cloud_icon.png";
                break;
            case "Snow":
                icon_path = "/welcome/weather_icons/snow_icon.png";
                break;
            case "Rain":
                icon_path = "/welcome/weather_icons/rain_icon.png";
                break;
            case "Drizzle":
                icon_path = "/welcome/weather_icons/drizzle_icon.png";
                break;
            case "Thunderstorm":
                icon_path = "/welcome/weather_icons/tstorm_icon.png";
                break;
            default:
                icon_path = "/welcome/weather_icons/atmosphere_icon.png";
        }
        
        //set label to selected icon

        //setIcon takes parameter ImageIcon,
        //icon.setIcon(new javax.swing.ImageIcon((getClass().getResource(icon_path))));
        
        javax.swing.ImageIcon img_icon = new javax.swing.ImageIcon((getClass().getResource(icon_path)));
        
        //conv imageicon to image, resize, then convert back to imageicon
        Image img = img_icon.getImage();
        Image scaled_img = img.getScaledInstance(icon.getWidth(),
                icon.getHeight(), Image.SCALE_DEFAULT);
        
        //conv back to icon
        javax.swing.ImageIcon scaled_icon = new javax.swing.ImageIcon(scaled_img);
        icon.setIcon(scaled_icon);
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(weathwmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(weathwmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(weathwmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(weathwmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new weathwmain().setVisible(true);
                
                
                //by default, London's weather is displayed in widget
                
                //weather_api.api_call(jComboBox1.getSelectedIndex)
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel current_temp;
    private javax.swing.JLabel feels_like;
    private javax.swing.JLabel icon;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel weather_text;
    // End of variables declaration//GEN-END:variables
}
